<?php

use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/shop', [HomeController::class, 'shop'])->name('shop');
Route::get('/cart', [HomeController::class, 'cart'])->name('cart');
Route::get('/checkout', [HomeController::class, 'checkout'])->name('checkout');
Route::post('/checkout', [HomeController::class, 'completeCheckout'])->name('checkout.complete');
Route::get('/dashboard', [HomeController::class, 'dashboard'])->name('dashboard');
Route::get('/dashboard/data', [HomeController::class, 'dashboardData'])->name('dashboard.data');
Route::post('/dashboard/orders/{reference}/cancel', [HomeController::class, 'cancelCustomerOrder'])->name('dashboard.orders.cancel');
Route::delete('/dashboard/addresses/{addressId}', [HomeController::class, 'deleteCustomerAddress'])->name('dashboard.addresses.destroy');
Route::post('/dashboard/profile', [HomeController::class, 'updateCustomerProfile'])->name('dashboard.profile.update');
Route::post('/dashboard/addresses', [HomeController::class, 'addCustomerAddress'])->name('dashboard.addresses.store');
Route::post('/dashboard/security', [HomeController::class, 'updateCustomerSecurity'])->name('dashboard.security.update');
Route::get('/logout', [HomeController::class, 'logoutCustomer'])->name('logout');
Route::get('/login', [HomeController::class, 'login'])->name('login');
Route::post('/login', [HomeController::class, 'authenticate'])->name('login.authenticate');
Route::get('/register', [HomeController::class, 'register'])->name('register');
Route::post('/register', [HomeController::class, 'createAccount'])->name('register.create');
Route::get('/contact', [HomeController::class, 'contact'])->name('contact');
Route::post('/contact', [HomeController::class, 'sendContactMessage'])->name('contact.send');
Route::get('/admin/login', [HomeController::class, 'adminLogin'])->name('admin.login');
Route::post('/admin/login', [HomeController::class, 'authenticateAdmin'])->name('admin.login.authenticate');
Route::get('/admin/logout', [HomeController::class, 'logoutAdmin'])->name('admin.logout');
Route::middleware('admin')->group(function () {
    Route::get('/admin/dashboard', [HomeController::class, 'adminDashboard'])->name('admin.dashboard');
    Route::get('/admin/inventory', [HomeController::class, 'adminInventory'])->name('admin.inventory');
    Route::get('/admin/library', [HomeController::class, 'adminLibrary'])->name('admin.library');
    Route::post('/admin/library', [HomeController::class, 'uploadLibraryImage'])->name('admin.library.upload');
    Route::post('/admin/inventory/undo', [HomeController::class, 'undoInventory'])->name('admin.inventory.undo');
    Route::post('/admin/inventory/redo', [HomeController::class, 'redoInventory'])->name('admin.inventory.redo');
    Route::post('/admin/inventory/products', [HomeController::class, 'createInventoryProduct'])->name('admin.inventory.products.store');
    Route::post('/admin/inventory/categories', [HomeController::class, 'createInventoryCategory'])->name('admin.inventory.categories.store');
    Route::put('/admin/inventory/products/{slug}', [HomeController::class, 'updateInventoryProduct'])->name('admin.inventory.products.update');
    Route::delete('/admin/inventory/products/{slug}', [HomeController::class, 'deleteInventoryProduct'])->name('admin.inventory.products.destroy');
    Route::post('/admin/inventory/products/{slug}/stock', [HomeController::class, 'updateInventoryStock'])->name('admin.inventory.products.stock');
    Route::post('/admin/inventory/products/{slug}/status', [HomeController::class, 'updateInventoryStatus'])->name('admin.inventory.products.status');
    Route::post('/admin/inventory/bulk', [HomeController::class, 'bulkInventoryAction'])->name('admin.inventory.bulk');
    Route::post('/admin/inventory/import', [HomeController::class, 'importInventory'])->name('admin.inventory.import');
    Route::get('/admin/inventory/export', [HomeController::class, 'exportInventory'])->name('admin.inventory.export');
    Route::get('/admin/orders', [HomeController::class, 'adminManager'])->defaults('section', 'orders')->name('admin.orders');
    Route::get('/admin/orders/waybills', [HomeController::class, 'printWaybills'])->name('admin.orders.waybills');
    Route::post('/admin/orders/bulk', [HomeController::class, 'bulkOrderAction'])->name('admin.orders.bulk');
    Route::post('/admin/orders/{reference}/status', [HomeController::class, 'updateOrderStatus'])->name('admin.orders.status');
    Route::get('/admin/products', [HomeController::class, 'adminManager'])->defaults('section', 'products')->name('admin.products');
    Route::get('/admin/products/{slug}/edit', [HomeController::class, 'editAdminProduct'])->name('admin.products.edit');
    Route::get('/admin/customers', [HomeController::class, 'adminManager'])->defaults('section', 'customers')->name('admin.customers');
    Route::get('/admin/discounts', [HomeController::class, 'adminManager'])->defaults('section', 'discounts')->name('admin.discounts');
    Route::post('/admin/discounts', [HomeController::class, 'createDiscount'])->name('admin.discounts.store');
    Route::get('/admin/reviews', [HomeController::class, 'adminManager'])->defaults('section', 'reviews')->name('admin.reviews');
    Route::get('/admin/analytics', [HomeController::class, 'adminManager'])->defaults('section', 'analytics')->name('admin.analytics');
    Route::get('/admin/settings', [HomeController::class, 'adminManager'])->defaults('section', 'settings')->name('admin.settings');
    Route::get('/admin/developer', [HomeController::class, 'adminManager'])->defaults('section', 'developer')->name('admin.developer');
    Route::post('/admin/developer', [HomeController::class, 'saveDeveloperSettings'])->name('admin.developer.save');
});
Route::get('/thank-you', [HomeController::class, 'thankYou'])->name('thank-you');
Route::get('/products/{slug}', [HomeController::class, 'product'])->name('products.show');
Route::post('/wishlist/{slug}', [HomeController::class, 'toggleWishlist'])->name('wishlist.toggle');
Route::post('/generate', [HomeController::class, 'generate'])->name('generate');
